# Generated by Django 6.0.5 on 2026-05-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('RESUME', '자소서 기반'), ('JOB', '직무 기반')], max_length=10)),
                ('question_count', models.IntegerField()),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', '생성됨'), ('CALIBRATED', '캘리브레이션 완료'), ('PROGRESS', '진행중'), ('ANALYZING', '분석중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='CREATED', max_length=20)),
                ('calibration_config', models.JSONField(blank=True, help_text='초기 캘리브레이션 기준값', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('video_path', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('ANALYZING', '분석중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('video_duration', models.FloatField(default=0.0)),
                ('gaze_front_ratio', models.FloatField(default=0.0)),
                ('gaze_deviation_ratio', models.FloatField(default=0.0)),
                ('body_sway_count', models.IntegerField(default=0)),
                ('shoulder_stability_ratio', models.FloatField(default=0.0)),
                ('blink_count', models.IntegerField(default=0)),
                ('nod_count', models.IntegerField(default=0)),
                ('smile_ratio', models.FloatField(default=0.0)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interview')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('interview', 'order')},
            },
        ),
    ]
