# Generated by Django 5.2.14 on 2026-05-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("RESUME", "자소서 기반"), ("JOB", "직무 기반")], max_length=10
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(default=3, help_text="사용자가 설정한 질문 개수"),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("job_group", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "분석중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(help_text="AI가 생성한 질문 내용", max_length=500),
                ),
                ("order", models.IntegerField(help_text="질문 순서 (1번 질문, 2번 질문...)")),
                (
                    "video_path",
                    models.FileField(
                        blank=True, null=True, upload_to="videos/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "분석중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interview.interview",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
