# Generated by Django 5.2.14 on 2026-05-10 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="question_count",
            field=models.IntegerField(
                help_text="사용자가 설정한 질문 개수",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
