# Generated by Django 6.0.5 on 2026-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_resume_remove_interview_resume_text_interview_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='resume',
        ),
        migrations.AddField(
            model_name='interview',
            name='resume_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
