# Generated by Django 5.2.14 on 2026-05-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("gaze_x", models.FloatField(help_text="눈동자 수평 위치")),
                ("gaze_y", models.FloatField(help_text="눈동자 수직 위치 (내리깔기 감지)")),
                ("head_yaw", models.FloatField(help_text="고개 좌우 회전")),
                ("head_pitch", models.FloatField(help_text="고개 상하 각도 (끄덕임/시선하락)")),
                ("head_roll", models.FloatField(help_text="고개 좌우 기울기 (갸우뚱)")),
                ("shoulder_tilt", models.FloatField(help_text="실시간 어깨 기울기 각도")),
                (
                    "shoulder_width",
                    models.FloatField(help_text="화면상 어깨 너비 (앞뒤 흔들림 감지용)"),
                ),
                ("center_x", models.FloatField(help_text="어깨 중앙점 X좌표 (좌우 흔들림 감지용)")),
                ("is_smiling", models.BooleanField(default=False)),
                (
                    "is_blink",
                    models.BooleanField(default=False, help_text="해당 프레임에서 눈을 감았는지"),
                ),
                ("gaze_direction", models.CharField(default="center", max_length=10)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_details",
                        to="interview.interviewquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BehaviorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("focus_rate", models.FloatField(help_text="전체 정면 응시율")),
                ("left_gaze_rate", models.FloatField(help_text="왼쪽 응시 비중")),
                ("right_gaze_rate", models.FloatField(help_text="오른쪽 응시 비중")),
                ("blinks_per_min", models.FloatField()),
                ("nod_count", models.IntegerField(help_text="고개 끄덕임 총 횟수")),
                ("shoulder_stability", models.FloatField(help_text="어깨 수평 유지율(%)")),
                ("lr_sway_count", models.IntegerField(help_text="좌우 흔들림 감지 횟수")),
                ("fb_sway_count", models.IntegerField(help_text="앞뒤 흔들림 감지 횟수")),
                ("total_smile_rate", models.FloatField()),
                ("start_smile_status", models.BooleanField()),
                ("end_smile_status", models.BooleanField()),
                ("overall_score", models.IntegerField()),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_report",
                        to="interview.interview",
                    ),
                ),
            ],
        ),
    ]
