# Generated by Django 5.2.14 on 2026-05-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField()),
                ("gaze_direction", models.CharField(default="center", max_length=10)),
                ("is_swaying", models.BooleanField(default=False)),
                ("is_blink", models.BooleanField(default=False)),
                ("is_nodding", models.BooleanField(default=False)),
                ("is_smiling", models.BooleanField(default=False)),
                ("shoulder_stable_frame", models.BooleanField(default=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="interview.interviewquestion",
                    ),
                ),
            ],
        ),
    ]
