# Generated by Django 5.2.14 on 2026-05-10 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="behaviorreport",
            old_name="question",
            new_name="interview",
        ),
    ]
