# Generated by Django 5.2.14 on 2026-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("behavior", "0002_rename_question_behaviorreport_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorreport",
            name="is_swaying",
            field=models.BooleanField(
                default=False, help_text="해당 프레임에서 몸의 흔들림이 감지되었는지"
            ),
        ),
    ]
