# Generated by Django 5.2.14 on 2026-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("behavior", "0003_behaviorreport_is_swaying"),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviordetail",
            name="is_swaying",
            field=models.BooleanField(default=False),
        ),
    ]
