# Generated by Django 6.0.5 on 2026-05-11 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
            ],
            options={
                'db_table': 'speech_analysis',
            },
        ),
        migrations.CreateModel(
            name='SpeechFiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('duration', models.FloatField()),
                ('filler_type', models.CharField(max_length=10)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillers', to='speech.speechanalysis')),
            ],
            options={
                'db_table': 'speech_filler',
            },
        ),
        migrations.CreateModel(
            name='SpeechReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('syllable_count', models.IntegerField()),
                ('duration_sec', models.FloatField()),
                ('spm', models.FloatField()),
                ('pace', models.CharField(max_length=20)),
                ('avg_db', models.FloatField()),
                ('max_db', models.FloatField()),
                ('min_db', models.FloatField()),
                ('std_db', models.FloatField()),
                ('volume_level', models.CharField(max_length=20)),
                ('filler_count', models.IntegerField()),
                ('frequent_fillers', models.JSONField(default=list)),
                ('volume_timeline', models.JSONField(default=list)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='speech.speechanalysis')),
            ],
            options={
                'db_table': 'speech_report',
            },
        ),
        migrations.CreateModel(
            name='SpeechSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('duration', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='speech.speechanalysis')),
            ],
            options={
                'db_table': 'speech_silence',
            },
        ),
    ]
