# Generated by Django 6.0.5 on 2026-05-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_count', models.IntegerField()),
            ],
            options={
                'db_table': 'speech_session',
            },
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='speech.speechsession'),
        ),
        migrations.CreateModel(
            name='SpeechSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_spm', models.FloatField()),
                ('pace', models.CharField(max_length=20)),
                ('avg_db', models.FloatField()),
                ('max_db', models.FloatField()),
                ('min_db', models.FloatField()),
                ('avg_std_db', models.FloatField()),
                ('volume_level', models.CharField(max_length=20)),
                ('total_filler_count', models.IntegerField()),
                ('frequent_fillers', models.JSONField(default=list)),
                ('total_silence_count', models.IntegerField()),
                ('avg_silence_duration', models.FloatField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='speech.speechsession')),
            ],
            options={
                'db_table': 'speech_session_report',
            },
        ),
    ]
