# Generated by Django 6.0.5 on 2026-05-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_speechsession_speechanalysis_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('order', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='speech.speechsession')),
            ],
            options={
                'db_table': 'speech_video_file',
                'ordering': ['order'],
            },
        ),
    ]
